// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCGAJAwbTiFE1HK_eGt_5pU_gP_cVDHIrM',
    appId: '1:352169315082:web:cbb2b99c4f223a16b5c8f3',
    messagingSenderId: '352169315082',
    projectId: 'flutter-chat-app-4a051',
    authDomain: 'flutter-chat-app-4a051.firebaseapp.com',
    storageBucket: 'flutter-chat-app-4a051.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDBL4i5X2s9nrWLtNRhZK3dDCeFMIU4XKw',
    appId: '1:352169315082:android:c8616171d9fb232ab5c8f3',
    messagingSenderId: '352169315082',
    projectId: 'flutter-chat-app-4a051',
    storageBucket: 'flutter-chat-app-4a051.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBSjoFXpiOUnCVsuS1m-4YLF_7Ix0dk6Mo',
    appId: '1:352169315082:ios:238a830d6c63d144b5c8f3',
    messagingSenderId: '352169315082',
    projectId: 'flutter-chat-app-4a051',
    storageBucket: 'flutter-chat-app-4a051.appspot.com',
    iosClientId: '352169315082-41vv93ksle34ru425vto5m0fvs43ik0b.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBSjoFXpiOUnCVsuS1m-4YLF_7Ix0dk6Mo',
    appId: '1:352169315082:ios:3cf3f85abe1fb364b5c8f3',
    messagingSenderId: '352169315082',
    projectId: 'flutter-chat-app-4a051',
    storageBucket: 'flutter-chat-app-4a051.appspot.com',
    iosClientId: '352169315082-2upk649k8qd4cg6nqd4vmit3ckqldujs.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp.RunnerTests',
  );
}
